godata:
  url:
    search: "http://apis.data.go.kr/1471000/FoodNtrIrdntInfoService1/getFoodNtrItdntList1"
  client:
    servicekey: H0jsiyFbcZgb4iYSKj1%2BCCdhFFNn9fTT083YmLYHc9OzYei6xxqs5f%2F9b87QeZ%2B0QEXnu2A7ztqBPR5ir7yYGw%3D%3D
    servicedeco: H0jsiyFbcZgb4iYSKj1+CCdhFFNn9fTT083YmLYHc9OzYei6xxqs5f/9b87QeZ+0QEXnu2A7ztqBPR5ir7yYGw==
server.port: 9090
spring.mvc.pathmatch.matching-strategy: ant_path_matcher

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/myfood?serverTimezone=Asia/Seoul
    username: azure
    password: azure1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      use-new-id-generate-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  database : mariadb

debug: false

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            test=DEBUG: